[package]
name = "google-gateway"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
litellm-contracts = { path = "../../crates/litellm-contracts" }
litellm-gateway = { path = "../../crates/litellm-gateway" }
